package pl.polsatgranie.smartmegane.domain.trip

data class TripLiveStats(
    val isActive: Boolean = false,
    val startedAtEpochMs: Long? = null,
    val durationMs: Long = 0L,
    val distanceKm: Double = 0.0,
    val fuelUsedLiters: Double = 0.0,
    val averageConsumptionLitersPer100Km: Double? = null,
    val instantFuelLitersPerHour: Double? = null,
    val instantConsumptionLitersPer100Km: Double? = null,
    val averageSpeedKph: Double = 0.0,
    val averageMovingSpeedKph: Double = 0.0,
    val maxSpeedKph: Double = 0.0,
    val movingDurationMs: Long = 0L,
    val idleDurationMs: Long = 0L,
    val averageRpm: Double = 0.0,
    val maxRpm: Int = 0,
    val maxCoolantTemperatureCelsius: Int? = null,
    val minOutsideTemperatureCelsius: Int? = null,
    val maxOutsideTemperatureCelsius: Int? = null,
    val startFuelPercent: Float? = null,
    val currentFuelPercent: Float? = null,
    val averageAcceleratorPercent: Float? = null,
    val maxAcceleratorPercent: Float? = null,
    val hardAccelerationCount: Int = 0,
    val hardBrakingCount: Int = 0,
    val maxUphillDegrees: Float? = null,
    val maxDownhillDegrees: Float? = null,
)

data class TripSummary(
    val id: Long,
    val startedAtEpochMs: Long,
    val endedAtEpochMs: Long,
    val durationMs: Long,
    val distanceKm: Double,
    val fuelUsedLiters: Double,
    val averageConsumptionLitersPer100Km: Double?,
    val averageSpeedKph: Double,
    val averageMovingSpeedKph: Double = 0.0,
    val maxSpeedKph: Double,
    val movingDurationMs: Long = 0L,
    val idleDurationMs: Long = 0L,
    val averageRpm: Double = 0.0,
    val maxRpm: Int = 0,
    val maxCoolantTemperatureCelsius: Int? = null,
    val minOutsideTemperatureCelsius: Int? = null,
    val maxOutsideTemperatureCelsius: Int? = null,
    val startFuelPercent: Float? = null,
    val endFuelPercent: Float? = null,
    val averageAcceleratorPercent: Float? = null,
    val maxAcceleratorPercent: Float? = null,
    val hardAccelerationCount: Int = 0,
    val hardBrakingCount: Int = 0,
    val maxUphillDegrees: Float? = null,
    val maxDownhillDegrees: Float? = null,
    val startOdometerKm: Long?,
    val endOdometerKm: Long?,
)
